language: python

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

env:
  - DJANGO=1.9 MIGRATE='./manage.py migrate'

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO

branches:
  only:
    - master
  
# command to run tests
script: $MIGRATE && ./manage.py test 
