# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 18:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpage',
            name='answers_expired',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='questionpage',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
