# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170430_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpage',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='questionpage',
            name='answers_before',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), default='{}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpage',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpage',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='answers_expired',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), default='{}', size=None),
            preserve_default=False,
        ),
    ]
