# Generated by Django 2.0.5 on 2018-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180513_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
