# Generated by Django 2.0.5 on 2018-05-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
    ]
