# Generated by Django 2.0.5 on 2018-05-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_track_is_discarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='instrument',
            field=models.CharField(choices=[('TRUMPET', 'Trumpet'), ('TROMBONE', 'Trombone'), ('SAXOPHONE', 'Saxophone'), ('TOUBA', 'Basses'), ('SOUBA', 'Souba'), ('DRUMS', 'Percus')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
