# Generated by Django 2.0.5 on 2018-05-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_people_instrument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('instrument', 'name'), 'verbose_name': 'Personne', 'verbose_name_plural': 'Personnes'},
        ),
        migrations.AlterField(
            model_name='people',
            name='instrument',
            field=models.CharField(choices=[('TRUMPET', 'Trompette'), ('TROMBONE', 'Trombone'), ('SAXOPHONE', 'Saxophone'), ('TOUBA', 'Basse'), ('SOUBA', 'Souba'), ('DRUMS', 'Percus')], max_length=255),
        ),
    ]
