# Generated by Django 2.0.5 on 2018-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180531_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',), 'verbose_name': 'évenement', 'verbose_name_plural': 'évenements'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('instrument', 'name'), 'verbose_name': 'personne', 'verbose_name_plural': 'personnes'},
        ),
        migrations.AlterModelOptions(
            name='questionpage',
            options={'ordering': ['start_date'], 'verbose_name': 'page "Est-ce que c\'est bientôt..."', 'verbose_name_plural': 'pages "Est-ce que c\'est bientôt..."'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='track',
            name='original_song_yt_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
