# Generated by Django 2.1 on 2018-10-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180603_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=255)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.People', verbose_name='who')),
            ],
        ),
    ]
